FROM php:5.6-apache

COPY ./container/000-default.conf /etc/apache2/sites-available/000-default.conf

RUN docker-php-ext-install mysqli 
RUN docker-php-ext-enable mysqli

RUN a2enmod rewrite
RUN a2enmod headers

RUN service apache2 restart
